services:
  cms_pg:
    image: postgres:16.1-alpine
    hostname: cms_pg
    container_name: cms_pg
    restart: unless-stopped
    env_file:
      - .env.database
    ports:
      - '5432:5432'
    volumes:
      - cms_pg:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d postgres']
      interval: 5s
      timeout: 2s
      retries: 20

  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
      target: backend
    image: cms_backend:latest
    container_name: cms_backend
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - '9090:9090'
    env_file:
      - ./apps/backend/.env.production
    depends_on:
      cms_pg:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      target: frontend
    image: cms_frontend:latest
    container_name: cms_frontend
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    env_file:
      - ./apps/frontend/.env.production
    depends_on:
      - backend
    networks:
      - app-network

  blog:
    build:
      context: .
      dockerfile: ./apps/blog/Dockerfile
      target: blog
    image: cms_blog:latest
    container_name: blog
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - ./apps/blog/.env.production
    ports:
      - '1024:1024'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  cms_pg:
